"""Initial migration

Revision ID: e73002b52a21
Revises: 
Create Date: 2023-11-23 16:43:08.616658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e73002b52a21"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("create schema ds")
    op.create_table(
        "champs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("id_dossier", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("string_value", sa.String(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="ds",
    )
    op.create_table(
        "demarche",
        sa.Column("id_demarche", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id_demarche"),
        schema="ds",
    )
    op.create_table(
        "dossier",
        sa.Column("id_dossier", sa.Integer(), nullable=False),
        sa.Column("id_demarche", sa.Integer(), nullable=False),
        sa.Column("statut", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_demarche"],
            ["ds.demarche.id_demarche"],
        ),
        sa.PrimaryKeyConstraint("id_dossier"),
        schema="ds",
    )
    op.create_table(
        "file",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("id_champ", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_champ"],
            ["ds.champs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="ds",
    )
    op.create_table(
        "geo_area",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("id_champ", sa.Integer(), nullable=False),
        sa.Column("geojson", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_champ"],
            ["ds.champs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="ds",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table("geo_area", schema="ds")
    op.drop_table("file", schema="ds")
    op.drop_table("dossier", schema="ds")
    op.drop_table("demarche", schema="ds")
    op.drop_table("champs", schema="ds")
    op.execute("drop schema ds")
    # ### end Alembic commands ###
